version: '3'

services:
  blog:
    image: blogs-docker:latest
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  sql:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true